
package com.jhmk.earlywaring.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HdrQueryDataService", targetNamespace = "http://ws.edi.hdr.goodwill.com/", wsdlLocation = "http://10.2.2.56:9010/hdr-edi/ws/hdrQueryDataWS?wsdl")
public class HdrQueryDataService
    extends Service
{

    private final static URL HDRQUERYDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException HDRQUERYDATASERVICE_EXCEPTION;
    private final static QName HDRQUERYDATASERVICE_QNAME = new QName("http://ws.edi.hdr.goodwill.com/", "HdrQueryDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.2.2.56:9010/hdr-edi/ws/hdrQueryDataWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HDRQUERYDATASERVICE_WSDL_LOCATION = url;
        HDRQUERYDATASERVICE_EXCEPTION = e;
    }

    public HdrQueryDataService() {
        super(__getWsdlLocation(), HDRQUERYDATASERVICE_QNAME);
    }

    public HdrQueryDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HDRQUERYDATASERVICE_QNAME, features);
    }

    public HdrQueryDataService(URL wsdlLocation) {
        super(wsdlLocation, HDRQUERYDATASERVICE_QNAME);
    }

    public HdrQueryDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HDRQUERYDATASERVICE_QNAME, features);
    }

    public HdrQueryDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HdrQueryDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HdrQueryDataWsImpl
     */
    @WebEndpoint(name = "HdrQueryDataWsImplPort")
    public HdrQueryDataWsImpl getHdrQueryDataWsImplPort() {
        return super.getPort(new QName("http://ws.edi.hdr.goodwill.com/", "HdrQueryDataWsImplPort"), HdrQueryDataWsImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HdrQueryDataWsImpl
     */
    @WebEndpoint(name = "HdrQueryDataWsImplPort")
    public HdrQueryDataWsImpl getHdrQueryDataWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.edi.hdr.goodwill.com/", "HdrQueryDataWsImplPort"), HdrQueryDataWsImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HDRQUERYDATASERVICE_EXCEPTION!= null) {
            throw HDRQUERYDATASERVICE_EXCEPTION;
        }
        return HDRQUERYDATASERVICE_WSDL_LOCATION;
    }

}
