
package com.jhmk.earlywaring.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HdrQueryDataWsImpl", targetNamespace = "http://ws.edi.hdr.goodwill.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HdrQueryDataWsImpl {


    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testWS", targetNamespace = "http://ws.edi.hdr.goodwill.com/", className = "com.goodwill.hdr.edi.ws.TestWS")
    @ResponseWrapper(localName = "testWSResponse", targetNamespace = "http://ws.edi.hdr.goodwill.com/", className = "com.goodwill.hdr.edi.ws.TestWSResponse")
    public Integer testWS();

    /**
     * 
     * @param pInput
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryData", targetNamespace = "http://ws.edi.hdr.goodwill.com/", className = "com.goodwill.hdr.edi.ws.QueryData")
    @ResponseWrapper(localName = "queryDataResponse", targetNamespace = "http://ws.edi.hdr.goodwill.com/", className = "com.goodwill.hdr.edi.ws.QueryDataResponse")
    public String queryData(
        @WebParam(name = "pInput", targetNamespace = "")
        String pInput);

}
