server:
  port: 8111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

url:
  cdssurl : http://192.168.8.20:8010
