server:
  port: 8111
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    url: jdbc:mysql://192.168.8.22:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    url: jdbc:mysql://192.168.132.4:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: root
    password: 123456
    max-active: 300
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
    validation-query: select 'x'

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

# 连接超时时间（毫秒）
  redis:
  # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    password:
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 0
url:
#  cdssurl : http://192.168.8.20:8011
  cdssurl : http://192.168.8.20:8010
#  cdssurl : http://192.168.132.7:8010