server:
#  port: 8111
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    url: jdbc:mysql://192.168.8.22:3306/jhmk_waring?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: root
    password: 123456
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

jwt:
  token:
    secret: zzy2018
